<html>
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
<h1>Меню</h1>
<div><a href="showrooms">Список автосалонов</a></div>
<div><a href="employees">Список сотрудников</a></div>
<div><a href="sellings">Список продаж</a></div>
<div><a href="cars">Список автомобилей</a></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>
